// Extract circomlib's standard Poseidon constants for BN254 t=3, VALIDATE them
// against the canonical poseidon([1,2]) test vector using the standard
// permutation (the same construction the Stellar host implements), then emit
// contracts/solvency/src/poseidon_params.rs. If validation fails, we abort and
// never emit anything (no unverified crypto).
import { buildPoseidon } from "circomlibjs";
import fs from "fs";

const poseidonConstants = JSON.parse(
  fs.readFileSync("node_modules/circomlibjs/src/poseidon_constants.json", "utf8")
);
const poseidon = await buildPoseidon();
const F = poseidon.F;

function un(o) {
  if (typeof o === "string") return F.e(o);
  if (Array.isArray(o)) return o.map(un);
  return o;
}
const C = un(poseidonConstants.C); // C[t-2] flat
const M = un(poseidonConstants.M); // M[t-2] t x t

const t = 3, RF = 8, RP = 57, N = RF + RP; // 65 rounds for t=3
const Ct = C[t - 2];
const Mt = M[t - 2];

// --- standard permutation (mirrors circomlibjs poseidon_reference.js) ---
const pow5 = a => F.mul(a, F.square(F.square(a)));
function permute(stateIn) {
  let state = stateIn.map(a => F.e(a));
  for (let r = 0; r < N; r++) {
    state = state.map((a, i) => F.add(a, Ct[r * t + i]));
    if (r < RF / 2 || r >= RF / 2 + RP) state = state.map(pow5);
    else state[0] = pow5(state[0]);
    state = state.map((_, i) => state.reduce((acc, a, j) => F.add(acc, F.mul(Mt[i][j], a)), F.zero));
  }
  return state;
}

// VALIDATE: permute([0,1,2])[0] must equal poseidon([1,2])
const ref = poseidon([1n, 2n]);
const got = permute([F.zero, F.e(1), F.e(2)])[0];
const refHex = "0x" + F.toObject(ref).toString(16);
const gotHex = "0x" + F.toObject(got).toString(16);
console.log("reference poseidon([1,2]) =", refHex);
console.log("my standard permute[0]   =", gotHex);
if (refHex !== gotHex) {
  console.error("VALIDATION FAILED — constants/construction mismatch. Aborting, nothing emitted.");
  process.exit(1);
}
console.log("VALIDATION PASSED — constants reproduce the canonical vector.");

// --- emit Rust ---
function be32(x) {
  const h = F.toObject(x).toString(16).padStart(64, "0");
  return Array.from({ length: 32 }, (_, i) => parseInt(h.substr(i * 2, 2), 16)).join(", ");
}
let out = "// AUTO-GENERATED by scripts/poseidon-gen.mjs. Do not edit.\n";
out += "// Standard Poseidon (BN254, t=3) constants from circomlib, VALIDATED against\n";
out += "// the canonical poseidon([1,2]) test vector before emission.\n\n";
out += `pub const T: u32 = ${t};\npub const D: u32 = 5;\npub const RF: u32 = ${RF};\npub const RP: u32 = ${RP};\npub const N_ROUNDS: usize = ${N};\n\n`;
// MDS 3x3
out += "pub const MDS: [[[u8; 32]; 3]; 3] = [\n";
for (let i = 0; i < 3; i++) {
  out += "  [";
  for (let j = 0; j < 3; j++) out += `[${be32(Mt[i][j])}], `;
  out += "],\n";
}
out += "];\n\n";
// RC N x 3
out += `pub const RC: [[[u8; 32]; 3]; ${N}] = [\n`;
for (let r = 0; r < N; r++) {
  out += "  [";
  for (let i = 0; i < 3; i++) out += `[${be32(Ct[r * t + i])}], `;
  out += "],\n";
}
out += "];\n\n";
out += `pub const REF_1_2: [u8; 32] = [${be32(ref)}];\n`;

fs.writeFileSync("contracts/solvency/src/poseidon_params.rs", out);
console.log("wrote contracts/solvency/src/poseidon_params.rs");
