// Converts snarkjs groth16 BLS12-381 output (decimal-string coordinates) into
// the arkworks uncompressed byte layout that the Soroban BLS12-381 host
// functions expect (G1 = 96 bytes, G2 = 192 bytes).
//
// Emits:
//   contracts/solvency/src/vk_data.rs  — VK byte constants embedded in the contract
//   build/invoke_args.json             — hex proof bytes + total for CLI invocation
//
// Usage: run from the converter dir; reads ../../build/{verification_key,proof,public}.json
use ark_bls12_381::{Fq, Fq2, G1Affine, G2Affine};
use ark_ff::PrimeField;
use ark_serialize::CanonicalSerialize;
use std::str::FromStr;

fn fq(s: &str) -> Fq {
    Fq::from_str(s).expect("bad Fq decimal string")
}

fn g1_bytes(coords: &serde_json::Value) -> [u8; 96] {
    let x = fq(coords[0].as_str().unwrap());
    let y = fq(coords[1].as_str().unwrap());
    let p = G1Affine::new(x, y);
    let mut buf = [0u8; 96];
    p.serialize_uncompressed(&mut buf[..]).unwrap();
    buf
}

fn g2_bytes(coords: &serde_json::Value) -> [u8; 192] {
    // snarkjs: [[x_c0, x_c1], [y_c0, y_c1], [z...]]
    let x = Fq2::new(fq(coords[0][0].as_str().unwrap()), fq(coords[0][1].as_str().unwrap()));
    let y = Fq2::new(fq(coords[1][0].as_str().unwrap()), fq(coords[1][1].as_str().unwrap()));
    let p = G2Affine::new(x, y);
    let mut buf = [0u8; 192];
    p.serialize_uncompressed(&mut buf[..]).unwrap();
    buf
}

fn fr_bytes_be(dec: &str) -> [u8; 32] {
    // Fr as 32-byte big-endian (matches U256 big-endian construction on-chain).
    let f = ark_bls12_381::Fr::from_str(dec).expect("bad Fr");
    let bi = f.into_bigint();
    let le = ark_ff::BigInteger::to_bytes_le(&bi);
    let mut be = [0u8; 32];
    for (i, b) in le.iter().enumerate() {
        be[31 - i] = *b;
    }
    be
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

fn rust_arr(name: &str, b: &[u8]) -> String {
    let items: Vec<String> = b.iter().map(|x| x.to_string()).collect();
    format!("pub const {}: [u8; {}] = [{}];\n", name, b.len(), items.join(", "))
}

fn main() {
    let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../build");
    let read = |f: &str| -> serde_json::Value {
        serde_json::from_str(&std::fs::read_to_string(base.join(f)).unwrap()).unwrap()
    };
    let vk = read("verification_key.json");
    let proof = read("proof.json");
    let public = read("public.json");

    // ---- VK constants embedded in the contract ----
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by scripts/converter. Do not edit by hand.\n");
    out.push_str("// Verification key for circuits/solvency.circom (BLS12-381 Groth16).\n\n");
    out.push_str(&rust_arr("VK_ALPHA", &g1_bytes(&vk["vk_alpha_1"])));
    out.push_str(&rust_arr("VK_BETA", &g2_bytes(&vk["vk_beta_2"])));
    out.push_str(&rust_arr("VK_GAMMA", &g2_bytes(&vk["vk_gamma_2"])));
    out.push_str(&rust_arr("VK_DELTA", &g2_bytes(&vk["vk_delta_2"])));
    let ic = vk["IC"].as_array().unwrap();
    out.push_str(&format!("pub const VK_IC_LEN: usize = {};\n", ic.len()));
    for (i, p) in ic.iter().enumerate() {
        out.push_str(&rust_arr(&format!("VK_IC{}", i), &g1_bytes(p)));
    }
    let vk_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../contracts/solvency/src/vk_data.rs");
    std::fs::write(&vk_path, out).unwrap();
    eprintln!("wrote {}", vk_path.display());

    // ---- proof + public args for CLI invocation ----
    let total = public[0].as_str().unwrap();
    let args = serde_json::json!({
        "proof_a": hex(&g1_bytes(&proof["pi_a"])),
        "proof_b": hex(&g2_bytes(&proof["pi_b"])),
        "proof_c": hex(&g1_bytes(&proof["pi_c"])),
        "total": total,
        "total_fr_be": hex(&fr_bytes_be(total)),
    });
    let args_path = base.join("invoke_args.json");
    std::fs::write(&args_path, serde_json::to_string_pretty(&args).unwrap()).unwrap();
    eprintln!("wrote {}", args_path.display());
    println!("{}", serde_json::to_string_pretty(&args).unwrap());
}
