// BN254 variant of the converter: snarkjs bn128 output -> arkworks uncompressed
// bytes for Stellar's BN254 host functions (G1 = 64 bytes, G2 = 128 bytes).
// Reads ../../build/bn254/{verification_key,proof,public}.json
// Emits contracts/solvency/src/vk_data_bn254.rs + build/bn254/invoke_args.json
use ark_bn254::Fq;
use ark_ff::{BigInteger, PrimeField};
use std::str::FromStr;

// Ethereum-compatible encoding (what Stellar's BN254 host functions expect):
// each field element is 32 bytes big-endian, no flags. G2 coordinates use the
// EIP-197 order (imaginary part c1 first, then real part c0).
fn fq_be(s: &str) -> [u8; 32] {
    let f = Fq::from_str(s).expect("bad Fq");
    let be = f.into_bigint().to_bytes_be(); // 32 bytes for BN254 Fq
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

fn g1_bytes(c: &serde_json::Value) -> [u8; 64] {
    let mut b = [0u8; 64];
    b[..32].copy_from_slice(&fq_be(c[0].as_str().unwrap())); // x
    b[32..].copy_from_slice(&fq_be(c[1].as_str().unwrap())); // y
    b
}
fn g2_bytes(c: &serde_json::Value) -> [u8; 128] {
    // snarkjs gives [[x_c0, x_c1], [y_c0, y_c1]]; Ethereum wants c1 then c0.
    let mut b = [0u8; 128];
    b[0..32].copy_from_slice(&fq_be(c[0][1].as_str().unwrap()));   // x_c1
    b[32..64].copy_from_slice(&fq_be(c[0][0].as_str().unwrap()));  // x_c0
    b[64..96].copy_from_slice(&fq_be(c[1][1].as_str().unwrap()));  // y_c1
    b[96..128].copy_from_slice(&fq_be(c[1][0].as_str().unwrap())); // y_c0
    b
}
fn hex(b: &[u8]) -> String { b.iter().map(|x| format!("{:02x}", x)).collect() }
fn rust_arr(name: &str, b: &[u8]) -> String {
    let items: Vec<String> = b.iter().map(|x| x.to_string()).collect();
    format!("pub const {}: [u8; {}] = [{}];\n", name, b.len(), items.join(", "))
}

fn main() {
    let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../build/bn254");
    let read = |f: &str| -> serde_json::Value {
        serde_json::from_str(&std::fs::read_to_string(base.join(f)).unwrap()).unwrap()
    };
    let vk = read("verification_key.json");
    let proof = read("proof.json");
    let public = read("public.json");

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by scripts/converter (BN254). Do not edit by hand.\n\n");
    out.push_str(&rust_arr("VK_ALPHA", &g1_bytes(&vk["vk_alpha_1"])));
    out.push_str(&rust_arr("VK_BETA", &g2_bytes(&vk["vk_beta_2"])));
    out.push_str(&rust_arr("VK_GAMMA", &g2_bytes(&vk["vk_gamma_2"])));
    out.push_str(&rust_arr("VK_DELTA", &g2_bytes(&vk["vk_delta_2"])));
    let ic = vk["IC"].as_array().unwrap();
    out.push_str(&format!("pub const VK_IC_LEN: usize = {};\n", ic.len()));
    for (i, p) in ic.iter().enumerate() {
        out.push_str(&rust_arr(&format!("VK_IC{}", i), &g1_bytes(p)));
    }
    let vk_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../contracts/solvency/src/vk_data_bn254.rs");
    std::fs::write(&vk_path, out).unwrap();
    eprintln!("wrote {}", vk_path.display());

    let total = public[0].as_str().unwrap();
    let args = serde_json::json!({
        "proof_a": hex(&g1_bytes(&proof["pi_a"])),
        "proof_b": hex(&g2_bytes(&proof["pi_b"])),
        "proof_c": hex(&g1_bytes(&proof["pi_c"])),
        "total": total,
    });
    std::fs::write(base.join("invoke_args.json"), serde_json::to_string_pretty(&args).unwrap()).unwrap();
    println!("{}", serde_json::to_string_pretty(&args).unwrap());
}
